const cities = [
    // 亚洲
    { english: "Tokyo", chinese: "东京" },
    { english: "Shanghai", chinese: "上海" },
    { english: "Beijing", chinese: "北京" },
    { english: "Seoul", chinese: "首尔" },
    { english: "Delhi", chinese: "新德里" },
    { english: "Mumbai", chinese: "孟买" },
    { english: "Karachi", chinese: "卡拉奇" },
    { english: "Istanbul", chinese: "伊斯坦布尔" },
    { english: "Moscow", chinese: "莫斯科" },
    { english: "Jakarta", chinese: "雅加达" },
    // 欧洲
    { english: "London", chinese: "伦敦" },
    { english: "Paris", chinese: "巴黎" },
    { english: "Madrid", chinese: "马德里" },
    { english: "Berlin", chinese: "柏林" },
    { english: "Rome", chinese: "罗马" },
    { english: "Athens", chinese: "雅典" },
    { english: "Amsterdam", chinese: "阿姆斯特丹" },
    { english: "Vienna", chinese: "维也纳" },
    { english: "Prague", chinese: "布拉格" },
    { english: "Stockholm", chinese: "斯德哥尔摩" },
    // 北美洲
    { english: "New York", chinese: "纽约" },
    { english: "Los Angeles", chinese: "洛杉矶" },
    { english: "Chicago", chinese: "芝加哥" },
    { english: "Toronto", chinese: "多伦多" },
    { english: "Mexico City", chinese: "墨西哥城" },
    { english: "Houston", chinese: "休斯顿" },
    { english: "Miami", chinese: "迈阿密" },
    { english: "San Francisco", chinese: "旧金山" },
    { english: "Washington", chinese: "华盛顿" },
    { english: "Vancouver", chinese: "温哥华" },
    // 南美洲
    { english: "São Paulo", chinese: "圣保罗" },
    { english: "Buenos Aires", chinese: "布宜诺斯艾利斯" },
    { english: "Rio de Janeiro", chinese: "里约热内卢" },
    { english: "Lima", chinese: "利马" },
    { english: "Bogotá", chinese: "波哥大" },
    { english: "Santiago", chinese: "圣地亚哥" },
    { english: "Caracas", chinese: "加拉加斯" },
    { english: "Quito", chinese: "基多" },
    { english: "Montevideo", chinese: "蒙得维的亚" },
    { english: "Brasília", chinese: "巴西利亚" },
    // 非洲
    { english: "Cairo", chinese: "开罗" },
    { english: "Lagos", chinese: "拉各斯" },
    { english: "Kinshasa", chinese: "金沙萨" },
    { english: "Johannesburg", chinese: "约翰内斯堡" },
    { english: "Nairobi", chinese: "内罗毕" },
    { english: "Addis Ababa", chinese: "亚的斯亚贝巴" },
    { english: "Casablanca", chinese: "卡萨布兰卡" },
    { english: "Cape Town", chinese: "开普敦" },
    { english: "Algiers", chinese: "阿尔及尔" },
    { english: "Dar es Salaam", chinese: "达累斯萨拉姆" },
    // 大洋洲
    { english: "Sydney", chinese: "悉尼" },
    { english: "Melbourne", chinese: "墨尔本" },
    { english: "Auckland", chinese: "奥克兰" },
    { english: "Brisbane", chinese: "布里斯班" },
    { english: "Perth", chinese: "珀斯" },
    { english: "Wellington", chinese: "惠灵顿" },
    { english: "Honolulu", chinese: "火奴鲁鲁" },
    { english: "Nouméa", chinese: "努美阿" },
    { english: "Suva", chinese: "苏瓦" },
    { english: "Pago Pago", chinese: "帕果帕果" }
  ];
  
  export default cities;
  